### PR TITLE
Switch to Java 22

### LINKED ISSUE #104: Switch to Java 22
Updating to Java 22 will no longer require passing `--enable-preview` everywhere, as among [other features](https://openjdk.org/projects/jdk/22/), it includes [JEP 454: Foreign Function & Memory API](https://openjdk.org/jeps/454) which is no longer a preview feature.

### PR DESCRIPTION
**Pull request by mizdebsk**
Switch to Java 22:
- Use non-preview [FFM API](https://openjdk.org/jeps/454)

Switch to java-deptools-native 1.2.0:
- This release contains significant performance improvements.
- It supports files without content (#86).

Closes #104

### CODE REVIEW

**Comment by mizdebsk** [comment]
CI shows error:
```
[ERROR] An exception occured:
java.lang.RuntimeException: java.io.IOException: Incomplete read in RPM stream
```
because java-deptools-native RpmArchiveInputStream can now return incomplete reads.

**Comment by mizdebsk** [comment]
Also duplicate files JP validator fails with multiple entries like:
```
[FAIL] File /usr/share/maven-poms/plexus provided by multiple RPMs: [plexus-archiver-4.9.1-4.fc41.noarch, plexus-cipher-2.0-12.fc41.noarch, plexus-interpolation-1.27-4.fc41.noarch, plexus-classworlds-2.8.0-4.fc41.noarch, plexus-build-api0-0.0.7-47.fc41.noarch, plexus-build-api-1.2.0-8.fc41.noarch, plexus-io-3.4.2-4.fc41.noarch, plexus-resources-1.3.0-4.fc41.noarch, plexus-utils-3.5.1-8.fc41.noarch, plexus-sec-dispatcher-2.0-14.fc41.noarch]
```
This is because java-deptools-native 1.2.0 now supports files with no contents (eg. directories like in the example above).

**Comment by mkoncek** [comment]
I don't see any problems with this change, I assume the added `<repositories>` are going to be removed before accepting the PR?
Also, the documentation (Build and Usage) will need to be updated, preferably after updating the documentation in the other PR.

**Comment by mizdebsk** [comment]
Now JP files fails with:
```
[FAIL] maven-1:3.9.6-7.fc41.noarch: Illegal file: /usr/bin/mvn
[FAIL] maven-1:3.9.6-7.fc41.noarch: Illegal file: /usr/bin/mvnDebug
```
Which indicates that validator can see ghost files (#86)

**Comment by mizdebsk** [comment]
CI failures were fixed in https://src.fedoraproject.org/tests/javapackages/c/a3f18d4

**Pull request merged**
